import mongoose from 'mongoose';

/*
 * Payment model
 * ------------------------------------------------------------
 * This model stores payment records separately from bookings.
 *
 * Why keep Payment separate from Booking?
 *
 * 1. A booking describes the reservation itself.
 * 2. A payment describes an attempt to pay for that reservation.
 * 3. One booking may have more than one payment attempt.
 *
 * Example:
 *
 * Booking:
 *   paymentStatus = "unpaid"
 *
 * First payment attempt:
 *   status = "failed"
 *
 * Second payment attempt:
 *   status = "paid"
 *
 * Booking:
 *   paymentStatus = "paid"
 *
 * Keeping these records separate gives us a proper payment
 * history instead of overwriting the details of old attempts.
 */

const paymentSchema = new mongoose.Schema(
  {
    /*
     * bookingType tells us what kind of booking this payment
     * belongs to.
     *
     * Right now Kusum's payment feature will use "hotel".
     *
     * "guide" is reserved for the future guide-booking feature.
     * We intentionally do NOT reference a GuideBooking model here
     * because that feature has not been implemented yet.
     */
    bookingType: {
      type: String,
      enum: {
        values: ['hotel', 'guide'],
        message: 'Invalid booking type.',
      },
      required: [true, 'Booking type is required.'],
      immutable: true,
    },

    /*
     * bookingId stores the MongoDB ID of the related booking.
     *
     * We intentionally keep this as a normal ObjectId instead
     * of using Mongoose refPath.
     *
     * This prevents Kusum's feature from depending on the name
     * or structure of Tafsir's future guide-booking model.
     *
     * For hotel payments, this ID points to the existing
     * Booking model.
     */
    bookingId: {
      type: mongoose.Schema.Types.ObjectId,
      required: [true, 'Booking ID is required.'],
      immutable: true,
      index: true,
    },

    /*
     * travelerId identifies the traveler who is making
     * the payment.
     *
     * The payment controller will take this from the
     * authenticated user instead of trusting an ID sent
     * by the frontend.
     */
    travelerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'Traveler ID is required.'],
      immutable: true,
      index: true,
    },

    /*
     * providerId identifies the hotel vendor or, in the future,
     * the guide receiving the booking.
     *
     * For a hotel booking this comes from booking.vendorId.
     */
    providerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'Provider ID is required.'],
      immutable: true,
      index: true,
    },

    /*
     * amount is a snapshot of the amount that must be paid.
     *
     * IMPORTANT:
     * The frontend must never decide this amount.
     *
     * For hotel payments, the backend will load the booking
     * from MongoDB and copy booking.totalPrice into this field.
     */
    amount: {
      type: Number,
      required: [true, 'Payment amount is required.'],
      min: [0, 'Payment amount cannot be negative.'],
      immutable: true,
    },

    /*
     * Ghuraghuri currently uses Bangladeshi Taka.
     *
     * Keeping currency in the payment record makes the record
     * clearer and prevents us from assuming the currency later.
     */
    currency: {
      type: String,
      enum: {
        values: ['BDT'],
        message: 'Invalid payment currency.',
      },
      default: 'BDT',
      immutable: true,
    },

    /*
     * gateway tells us which payment service handled
     * this payment attempt.
     *
     * Kusum's first implementation will use SSLCommerz sandbox.
     *
     * bKash remains available in the schema because the official
     * project requirements mention SSLCommerz / bKash sandbox.
     * We are not implementing bKash yet.
     */
    gateway: {
      type: String,
      enum: {
        values: ['sslcommerz', 'bkash'],
        message: 'Invalid payment gateway.',
      },
      default: 'sslcommerz',
      immutable: true,
    },

    /*
     * transactionId is generated by OUR backend before asking
     * the payment gateway to create a payment session.
     *
     * Every payment attempt gets a different transaction ID.
     *
     * unique: true prevents the same transaction ID from being
     * used for two payment records.
     */
    transactionId: {
      type: String,
      required: [true, 'Transaction ID is required.'],
      trim: true,
      unique: true,
      index: true,
      immutable: true,
    },

    /*
     * SSLCommerz returns a session key after a successful
     * payment-session initialization.
     *
     * It does not exist when the Payment document is first
     * created, so null is allowed.
     */
    gatewaySessionKey: {
      type: String,
      default: null,
      trim: true,
    },

    /*
     * The gateway can later provide a validation ID when
     * payment verification succeeds.
     *
     * We store it so the successful payment can be traced
     * during development, testing, and viva demonstration.
     */
    gatewayValidationId: {
      type: String,
      default: null,
      trim: true,
    },

    /*
     * The gateway may also provide its own banking/payment
     * transaction identifier.
     *
     * This is different from transactionId above:
     *
     * transactionId
     *   = generated by Ghuraghuri
     *
     * gatewayBankTransactionId
     *   = returned by the payment gateway
     */
    gatewayBankTransactionId: {
      type: String,
      default: null,
      trim: true,
    },

    /*
     * gatewayStatus stores the gateway's status text when useful.
     *
     * Our application still uses the normalized "status" field
     * below when deciding whether the payment succeeded.
     */
    gatewayStatus: {
      type: String,
      default: null,
      trim: true,
    },

    /*
     * status represents the lifecycle of THIS payment attempt.
     *
     * initiated:
     *   A local payment record exists and payment has started.
     *
     * paid:
     *   The gateway payment has been successfully verified.
     *
     * failed:
     *   The payment attempt failed.
     *
     * cancelled:
     *   The traveler cancelled the gateway checkout.
     *
     * refunded:
     *   A previously successful payment has been refunded.
     *
     * Notice that this is different from:
     *
     * booking.paymentStatus
     *
     * Payment.status tracks an individual payment attempt.
     * Booking.paymentStatus gives the current payment state
     * of the booking.
     */
    status: {
      type: String,
      enum: {
        values: [
          'initiated',
          'paid',
          'failed',
          'cancelled',
          'refunded',
        ],
        message: 'Invalid payment status.',
      },
      default: 'initiated',
      index: true,
    },

    /*
     * These timestamps make payment history easier to understand
     * and make debugging/demoing gateway callbacks much easier.
     *
     * They start as null and are filled only when that event
     * actually occurs.
     */
    paidAt: {
      type: Date,
      default: null,
    },

    failedAt: {
      type: Date,
      default: null,
    },

    cancelledAt: {
      type: Date,
      default: null,
    },

    refundedAt: {
      type: Date,
      default: null,
    },
  },
  {
    /*
     * Mongoose automatically creates:
     *
     * createdAt
     * updatedAt
     *
     * These are especially useful for payment history.
     */
    timestamps: true,
  }
);

/*
 * Quickly retrieve all payment attempts for one booking.
 *
 * A booking can have multiple payment attempts, so bookingId
 * is intentionally NOT unique.
 */
paymentSchema.index({
  bookingType: 1,
  bookingId: 1,
  createdAt: -1,
});

/*
 * Traveler payment history:
 *
 * newest payment attempts first.
 */
paymentSchema.index({
  travelerId: 1,
  createdAt: -1,
});

/*
 * Provider payment history:
 *
 * lets a hotel vendor later see payments associated with
 * their bookings.
 */
paymentSchema.index({
  providerId: 1,
  createdAt: -1,
});

/*
 * Useful when looking for recent successful/failed payments.
 */
paymentSchema.index({
  status: 1,
  createdAt: -1,
});

const Payment = mongoose.model(
  'Payment',
  paymentSchema
);

export default Payment;