import mongoose from 'mongoose';

/*
 * ------------------------------------------------------------
 * RAFI FEATURE 3 - PREMIUM PAYMENT MODEL
 * ------------------------------------------------------------
 *
 * This model stores payment attempts made specifically for:
 *
 *   Traveler -> Upgrade Account -> Premium Membership
 *
 * This is intentionally DIFFERENT from Kusum/Fatema's existing:
 *
 *   payment.model.js
 *
 * Her Payment model represents BOOKING payments and contains
 * fields such as:
 *
 *   bookingId
 *   bookingType
 *   providerId
 *
 * A Premium upgrade has no hotel booking and no hotel vendor.
 *
 * Therefore, trying to force a Premium purchase into the
 * existing booking-payment model would mix two different
 * business concepts.
 *
 * Instead:
 *
 *   Booking payment  -> Payment
 *   Premium upgrade  -> PremiumPayment
 *
 * Both can still communicate with the same SSLCOMMERZ sandbox
 * service later.
 *
 * This keeps Rafi's feature separated from another member's
 * payment feature.
 */


/*
 * These are the states one Premium payment attempt may have.
 *
 * initiated:
 *   We created the payment locally and asked SSLCOMMERZ to
 *   start checkout.
 *
 * paid:
 *   SSLCOMMERZ payment was successfully validated.
 *
 * failed:
 *   Gateway checkout failed.
 *
 * cancelled:
 *   Traveler cancelled the hosted checkout.
 *
 * refunded:
 *   Reserved for a successful payment that is later refunded.
 */
const PREMIUM_PAYMENT_STATUSES = [
  'initiated',
  'paid',
  'failed',
  'cancelled',
  'refunded',
];


const premiumPaymentSchema =
  new mongoose.Schema(
    {
      /*
       * travelerId
       * ------------------------------------------------------
       *
       * This identifies WHO is attempting to purchase Premium.
       *
       * Later the controller will get this value from:
       *
       *   req.user._id
       *
       * We will NOT trust a traveler ID coming from the browser.
       *
       * That prevents one traveler from trying to purchase or
       * manipulate Premium membership for another traveler.
       */
      travelerId: {
        type:
          mongoose.Schema.Types.ObjectId,

        ref: 'User',

        required: [
          true,
          'Traveler ID is required for a Premium payment.',
        ],

        immutable: true,

        index: true,
      },


      /*
       * amount
       * ------------------------------------------------------
       *
       * This stores the Premium upgrade price at the moment the
       * payment attempt is created.
       *
       * Default settings currently say:
       *
       *   499 BDT
       *
       * However, the frontend will never be trusted to provide
       * this amount.
       *
       * The future Premium controller will load the authoritative
       * value from RewardSettings.
       *
       * We then save a snapshot here because a transaction should
       * continue representing the amount that was actually sent
       * to SSLCOMMERZ, even if an administrator changes the
       * Premium price later.
       */
      amount: {
        type: Number,

        required: [
          true,
          'Premium payment amount is required.',
        ],

        min: [
          10,
          'Premium payment amount must be at least 10 BDT.',
        ],

        immutable: true,
      },


      /*
       * Ghuraghuri currently charges in Bangladeshi Taka.
       *
       * We explicitly store the currency instead of assuming it
       * when reviewing old payment records.
       */
      currency: {
        type: String,

        enum: {
          values: [
            'BDT',
          ],

          message:
            'Premium payments currently support BDT only.',
        },

        default: 'BDT',

        immutable: true,
      },


      /*
       * gateway
       * ------------------------------------------------------
       *
       * Rafi's Premium implementation will initially reuse the
       * project's existing SSLCOMMERZ sandbox integration.
       *
       * We are not claiming to implement another gateway here.
       */
      gateway: {
        type: String,

        enum: {
          values: [
            'sslcommerz',
          ],

          message:
            'Premium payments currently support SSLCOMMERZ only.',
        },

        default: 'sslcommerz',

        immutable: true,
      },


      /*
       * transactionId
       * ------------------------------------------------------
       *
       * This ID is generated by OUR backend before we create the
       * SSLCOMMERZ session.
       *
       * Example conceptually:
       *
       *   PRM-A1B2C3D4...
       *
       * It lets us match a callback from SSLCOMMERZ to the exact
       * PremiumPayment document in MongoDB.
       *
       * unique: true means two payment attempts cannot share the
       * same transaction ID.
       */
      transactionId: {
        type: String,

        required: [
          true,
          'Premium payment transaction ID is required.',
        ],

        trim: true,

        unique: true,

        index: true,

        immutable: true,
      },


      /*
       * gatewaySessionKey
       * ------------------------------------------------------
       *
       * After a payment session is successfully created,
       * SSLCOMMERZ returns a session key.
       *
       * We cannot know it when this MongoDB document is first
       * created, so null is allowed initially.
       */
      gatewaySessionKey: {
        type: String,

        trim: true,

        default: null,
      },


      /*
       * gatewayValidationId
       * ------------------------------------------------------
       *
       * A success redirect is NOT enough proof that payment
       * succeeded.
       *
       * SSLCOMMERZ gives us a validation ID.
       *
       * Our backend later sends this ID back to SSLCOMMERZ's
       * validation API before activating Premium membership.
       */
      gatewayValidationId: {
        type: String,

        trim: true,

        default: null,
      },


      /*
       * gatewayBankTransactionId
       * ------------------------------------------------------
       *
       * SSLCOMMERZ/payment-provider infrastructure may return its
       * own transaction identifier.
       *
       * This is separate from transactionId above.
       *
       * transactionId:
       *   generated by Ghuraghuri
       *
       * gatewayBankTransactionId:
       *   returned by payment infrastructure
       */
      gatewayBankTransactionId: {
        type: String,

        trim: true,

        default: null,
      },


      /*
       * gatewayStatus
       * ------------------------------------------------------
       *
       * This stores useful status text returned by SSLCOMMERZ.
       *
       * Our application does NOT use arbitrary gateway text as
       * its main business status.
       *
       * The normalized "status" field below remains the value
       * our application understands.
       */
      gatewayStatus: {
        type: String,

        trim: true,

        default: null,
      },


      /*
       * status
       * ------------------------------------------------------
       *
       * This is Ghuraghuri's normalized status for this Premium
       * payment attempt.
       */
      status: {
        type: String,

        enum: {
          values:
            PREMIUM_PAYMENT_STATUSES,

          message:
            'Invalid Premium payment status.',
        },

        default: 'initiated',

        index: true,
      },


      /*
       * Event timestamps
       * ------------------------------------------------------
       *
       * These are null until the corresponding event happens.
       *
       * Having separate timestamps makes payment history easier
       * to understand and demonstrate during viva.
       */
      paidAt: {
        type: Date,

        default: null,
      },

      failedAt: {
        type: Date,

        default: null,
      },

      cancelledAt: {
        type: Date,

        default: null,
      },

      refundedAt: {
        type: Date,

        default: null,
      },
    },
    {
      /*
       * Automatically creates:
       *
       *   createdAt
       *   updatedAt
       */
      timestamps: true,
    }
  );


/*
 * This index makes queries such as:
 *
 *   "Show this traveler's newest Premium payment attempts"
 *
 * efficient.
 */
premiumPaymentSchema.index({
  travelerId: 1,
  createdAt: -1,
});


/*
 * This index helps when reviewing payment attempts by their
 * normalized state.
 *
 * Example:
 *
 *   all paid Premium payments
 *   all failed Premium payments
 */
premiumPaymentSchema.index({
  status: 1,
  createdAt: -1,
});


const PremiumPayment =
  mongoose.model(
    'PremiumPayment',
    premiumPaymentSchema
  );


export {
  PREMIUM_PAYMENT_STATUSES,
};

export default PremiumPayment;