import {
  randomBytes,
} from 'node:crypto';

import PremiumMembership from '../models/premiumMembership.model.js';
import PremiumPayment from '../models/premiumPayment.model.js';

import {
  getPremiumMembershipByTravelerId,
} from './premium-membership.service.js';

import {
  getRewardSettings,
} from './reward-settings.service.js';

import {
  createPremiumPaymentSession,
  validatePayment,
} from './sslcommerz.service.js';


/*
 * ============================================================
 * RAFI FEATURE 3 - PREMIUM PAYMENT SERVICE
 * ============================================================
 *
 * This service contains the business logic for Premium-account
 * upgrade payments.
 *
 *
 * It is intentionally separate from Fatema/Kusum's existing:
 *
 *   payment.controller.js
 *   payment.model.js
 *
 *
 * Why?
 *
 * Their Payment model represents payments for BOOKINGS.
 *
 * Booking payments have concepts such as:
 *
 *   bookingId
 *   providerId
 *   bookingType
 *
 *
 * A Premium upgrade has none of those concepts.
 *
 * Therefore:
 *
 *   Hotel/guide booking payment
 *       -> Payment model
 *
 *   Premium account upgrade
 *       -> PremiumPayment model
 *
 *
 * Both systems still reuse:
 *
 *   sslcommerz.service.js
 *
 * for communication with the same SSLCOMMERZ sandbox.
 *
 *
 * This service currently handles:
 *
 *   1. Starting a Premium payment.
 *   2. Finding a Premium payment from callback information.
 *   3. Validating a successful payment with SSLCOMMERZ.
 *   4. Marking a Premium payment as paid.
 *   5. Creating the PremiumMembership.
 *   6. Recording failed/cancelled Premium payment attempts.
 *
 *
 * It does NOT yet:
 *
 *   - award reward points
 *   - calculate historical booking rewards
 *   - consume reward points
 *
 * Those belong to the reward portion of Rafi Feature 3 and will
 * be added separately.
 */


/*
 * ------------------------------------------------------------
 * ACTIVE PREMIUM CHECKOUT WINDOW
 * ------------------------------------------------------------
 *
 * We do not want a traveler to accidentally open many Premium
 * checkout sessions at once.
 *
 * An initiated Premium payment is therefore considered active
 * for 30 minutes.
 *
 *
 * Example:
 *
 * 1:00 PM
 * User starts checkout.
 *
 * 1:05 PM
 * User clicks Upgrade again.
 *
 * We reject the second attempt because the first attempt is
 * still active.
 *
 *
 * If an initiated local attempt is older than 30 minutes, we
 * mark that local attempt cancelled and allow a new one.
 *
 * This affects ONLY Rafi's PremiumPayment records.
 */
const ACTIVE_PREMIUM_PAYMENT_MINUTES =
  30;

const ACTIVE_PREMIUM_PAYMENT_WINDOW_MS =
  ACTIVE_PREMIUM_PAYMENT_MINUTES *
  60 *
  1000;


/*
 * ------------------------------------------------------------
 * HTTP ERROR HELPER
 * ------------------------------------------------------------
 *
 * The project's centralized error middleware checks:
 *
 *   error.statusCode
 *
 * Therefore we attach an HTTP status code to a normal
 * JavaScript Error object.
 */
function createHttpError(
  message,
  statusCode
) {
  const error =
    new Error(message);

  error.statusCode =
    statusCode;

  return error;
}


/*
 * ------------------------------------------------------------
 * MONEY COMPARISON HELPER
 * ------------------------------------------------------------
 *
 * JavaScript decimal numbers may sometimes contain tiny
 * floating-point differences.
 *
 * Example:
 *
 *   499
 *
 * and:
 *
 *   499.00
 *
 * obviously represent the same amount.
 *
 *
 * To compare money safely, we convert both values to cents:
 *
 *   499.00 × 100 = 49900
 *
 * and compare the rounded integers.
 *
 *
 * This follows the same basic idea already used by the existing
 * booking-payment feature.
 */
function amountsMatch(
  firstAmount,
  secondAmount
) {
  const first =
    Number(firstAmount);

  const second =
    Number(secondAmount);

  if (
    !Number.isFinite(first) ||
    !Number.isFinite(second)
  ) {
    return false;
  }

  return (
    Math.round(first * 100) ===
    Math.round(second * 100)
  );
}


/*
 * ------------------------------------------------------------
 * GENERATE PREMIUM TRANSACTION ID
 * ------------------------------------------------------------
 *
 * SSLCOMMERZ requires a unique transaction ID.
 *
 * The ID is generated by OUR backend rather than accepting one
 * from the browser.
 *
 *
 * Example:
 *
 *   PRMm9x2abc1234567890
 *
 *
 * "PRM" makes Premium transactions easy to recognize while
 * debugging.
 *
 * Date.now().toString(36) gives us a compact time component.
 *
 * randomBytes() adds randomness so transactions created close
 * together still receive different identifiers.
 */
function generatePremiumTransactionId() {
  const timePart =
    Date.now().toString(36);

  const randomPart =
    randomBytes(5)
      .toString('hex');

  return `PRM${timePart}${randomPart}`;
}


/*
 * ------------------------------------------------------------
 * FIND PREMIUM PAYMENT BY TRANSACTION ID
 * ------------------------------------------------------------
 *
 * SSLCOMMERZ callbacks do NOT contain the traveler's normal
 * Ghuraghuri login cookie.
 *
 * Therefore callback processing cannot identify the payment by:
 *
 *   req.user
 *
 *
 * Instead, every Premium checkout has the backend-generated:
 *
 *   transactionId
 *
 *
 * SSLCOMMERZ returns that same value as:
 *
 *   tran_id
 *
 *
 * This helper finds the corresponding PremiumPayment record.
 */
async function findPremiumPaymentByTransactionId(
  transactionId
) {
  /*
   * Reject missing or empty IDs before querying MongoDB.
   */
  if (
    typeof transactionId !== 'string' ||
    !transactionId.trim()
  ) {
    throw createHttpError(
      'Premium payment transaction ID is required.',
      400
    );
  }


  const payment =
    await PremiumPayment.findOne({
      transactionId:
        transactionId.trim(),
    });


  if (!payment) {
    throw createHttpError(
      'Premium payment transaction was not found.',
      404
    );
  }


  return payment;
}


/*
 * ------------------------------------------------------------
 * EXPIRE OLD UNFINISHED PREMIUM PAYMENT ATTEMPTS
 * ------------------------------------------------------------
 *
 * A traveler may open SSLCOMMERZ checkout and then close the
 * browser without pressing Cancel.
 *
 * The local PremiumPayment could remain:
 *
 *   initiated
 *
 * indefinitely.
 *
 *
 * Before starting another Premium payment, we therefore mark
 * sufficiently old local attempts as cancelled.
 *
 *
 * IMPORTANT:
 *
 * This does NOT touch:
 *
 *   Fatema's Payment collection
 *   hotel bookings
 *   guide bookings
 *
 * It updates only PremiumPayment documents.
 */
async function expireOldPremiumPaymentAttempts(
  travelerId
) {
  const now =
    new Date();

  const activeCutoff =
    new Date(
      now.getTime() -
      ACTIVE_PREMIUM_PAYMENT_WINDOW_MS
    );


  await PremiumPayment.updateMany(
    {
      travelerId,

      status:
        'initiated',

      createdAt: {
        $lt:
          activeCutoff,
      },
    },

    {
      $set: {
        status:
          'cancelled',

        gatewayStatus:
          'LOCAL_SESSION_EXPIRED',

        cancelledAt:
          now,
      },
    }
  );
}


/*
 * ------------------------------------------------------------
 * FIND ACTIVE PREMIUM PAYMENT ATTEMPT
 * ------------------------------------------------------------
 *
 * After old attempts are cleaned up, we check whether a recent
 * initiated attempt still exists.
 *
 * If it does, another checkout is not created.
 *
 * This reduces accidental duplicate Premium purchases.
 */
async function findActivePremiumPaymentAttempt(
  travelerId
) {
  const activeCutoff =
    new Date(
      Date.now() -
      ACTIVE_PREMIUM_PAYMENT_WINDOW_MS
    );


  const payment =
    await PremiumPayment.findOne({
      travelerId,

      status:
        'initiated',

      createdAt: {
        $gte:
          activeCutoff,
      },
    })
      .sort({
        createdAt: -1,
      });


  return payment;
}


/*
 * ------------------------------------------------------------
 * ENSURE PREMIUM MEMBERSHIP EXISTS
 * ------------------------------------------------------------
 *
 * A successful and verified PremiumPayment should create exactly
 * ONE PremiumMembership for the traveler.
 *
 *
 * The word "ensure" is important.
 *
 * We do not simply call:
 *
 *   PremiumMembership.create(...)
 *
 * every time a callback arrives.
 *
 *
 * Why?
 *
 * Payment gateways may send the same notification more than
 * once.
 *
 * The browser success callback may also happen around the same
 * time as the server-to-server IPN callback.
 *
 *
 * If both requests tried to create a membership independently,
 * we might encounter duplicate records.
 *
 *
 * Instead we use:
 *
 *   findOneAndUpdate()
 *   +
 *   upsert
 *   +
 *   $setOnInsert
 *
 *
 * Meaning:
 *
 *   If membership already exists:
 *      return it unchanged.
 *
 *   If membership does not exist:
 *      create it.
 *
 *
 * This makes Premium activation idempotent.
 */
async function ensurePremiumMembershipForPayment(
  payment
) {
  /*
   * Premium should only be activated from a payment that our
   * backend has already marked as successfully validated.
   */
  if (
    payment.status !== 'paid'
  ) {
    throw createHttpError(
      'Premium membership cannot be activated from an unpaid transaction.',
      409
    );
  }


  /*
   * Use the payment's verified paidAt time as the membership
   * activation time.
   *
   * If paidAt somehow does not exist, use the current time as a
   * defensive fallback.
   */
  const activatedAt =
    payment.paidAt ||
    new Date();


  const membership =
    await PremiumMembership.findOneAndUpdate(
      /*
       * A traveler may own only one Premium membership.
       */
      {
        travelerId:
          payment.travelerId,
      },

      /*
       * These values are written ONLY if MongoDB has to create
       * the membership.
       *
       * If the membership already exists, we never replace the
       * original activation payment or reset point balances.
       */
      {
        $setOnInsert: {
          travelerId:
            payment.travelerId,

          upgradePaymentId:
            payment._id,

          activatedAt,
        },
      },

      {
        /*
         * Create the membership if it does not exist.
         */
        upsert: true,

        /*
         * Return the final document.
         */
        new: true,

        /*
         * Apply defaults from premiumMembership.model.js.
         *
         * Initially this gives:
         *
         * rewardPoints = 0
         * lifetimePointsEarned = 0
         * lifetimePointsRedeemed = 0
         * historicalRewardsInitializedAt = null
         */
        setDefaultsOnInsert: true,

        /*
         * Apply Mongoose validation rules.
         */
        runValidators: true,
      }
    );


  return membership;
}


/*
 * ------------------------------------------------------------
 * VERIFY AND COMPLETE PREMIUM PAYMENT
 * ------------------------------------------------------------
 *
 * This is the most security-sensitive function in Rafi's
 * Premium upgrade flow.
 *
 *
 * A browser arriving at:
 *
 *   /sslcommerz/success
 *
 * is NOT enough proof that payment succeeded.
 *
 *
 * Correct flow:
 *
 * SSLCOMMERZ sends:
 *
 *   tran_id
 *   val_id
 *
 *            ↓
 *
 * We locate our PremiumPayment using tran_id.
 *
 *            ↓
 *
 * We send val_id BACK to SSLCOMMERZ using validatePayment().
 *
 *            ↓
 *
 * SSLCOMMERZ returns authoritative transaction information.
 *
 *            ↓
 *
 * We compare:
 *
 *   gateway status
 *   transaction ID
 *   amount
 *   currency
 *
 *            ↓
 *
 * Only then:
 *
 *   PremiumPayment.status = paid
 *
 *            ↓
 *
 * PremiumMembership is created.
 *
 *
 * This is exactly why someone cannot simply edit a frontend
 * request and declare themselves Premium.
 */
async function verifyAndCompletePremiumPayment({
  transactionId,
  validationId,
}) {
  /*
   * Load our own trusted PremiumPayment record.
   */
  const payment =
    await findPremiumPaymentByTransactionId(
      transactionId
    );


  /*
   * ----------------------------------------------------------
   * IDEMPOTENCY CASE
   * ----------------------------------------------------------
   *
   * If we already validated this payment earlier, we do not call
   * SSLCOMMERZ or charge/reprocess anything again.
   *
   *
   * However, we STILL run:
   *
   *   ensurePremiumMembershipForPayment()
   *
   * below.
   *
   * Why?
   *
   * Imagine:
   *
   * 1. Payment is successfully marked paid.
   * 2. Server unexpectedly stops before membership is created.
   * 3. SSLCOMMERZ sends the callback again.
   *
   * Because we continue to the membership step, the second
   * callback can safely repair that incomplete state.
   */
  if (
    payment.status !== 'paid'
  ) {
    /*
     * A successful Premium payment must contain the Validation
     * ID that SSLCOMMERZ gave us.
     */
    if (
      typeof validationId !== 'string' ||
      !validationId.trim()
    ) {
      throw createHttpError(
        'Premium payment validation ID is required.',
        400
      );
    }


    /*
     * Ask SSLCOMMERZ itself for authoritative information.
     *
     * validatePayment() already belongs to the shared gateway
     * service and is also used by the existing booking-payment
     * feature.
     *
     * We are reusing it rather than copying gateway-validation
     * code into Rafi's feature.
     */
    const validation =
      await validatePayment(
        validationId.trim()
      );


    /*
     * SSLCOMMERZ uses VALID / VALIDATED for successful validated
     * transactions.
     */
    const successfulStatuses =
      new Set([
        'VALID',
        'VALIDATED',
      ]);


    const validationStatus =
      String(
        validation.status || ''
      ).toUpperCase();


    if (
      !successfulStatuses.has(
        validationStatus
      )
    ) {
      throw createHttpError(
        'SSLCOMMERZ did not validate this Premium transaction as successful.',
        400
      );
    }


    /*
     * --------------------------------------------------------
     * SECURITY CHECK 1 - TRANSACTION ID
     * --------------------------------------------------------
     *
     * SSLCOMMERZ's validated tran_id must match the transaction
     * ID stored in our PremiumPayment document.
     */
    if (
      validation.tran_id !==
      payment.transactionId
    ) {
      throw createHttpError(
        'Premium payment transaction ID validation failed.',
        400
      );
    }


    /*
     * --------------------------------------------------------
     * SECURITY CHECK 2 - AMOUNT
     * --------------------------------------------------------
     *
     * The amount returned by SSLCOMMERZ must match the amount
     * stored in PremiumPayment.
     *
     *
     * Remember:
     *
     * PremiumPayment.amount was originally copied from the
     * backend RewardSettings document.
     *
     * The browser never chose this amount.
     */
    if (
      !amountsMatch(
        validation.amount,
        payment.amount
      )
    ) {
      throw createHttpError(
        'Premium payment amount validation failed.',
        400
      );
    }


    /*
     * --------------------------------------------------------
     * SECURITY CHECK 3 - CURRENCY
     * --------------------------------------------------------
     *
     * Ghuraghuri currently uses BDT.
     *
     * SSLCOMMERZ responses normally provide "currency".
     *
     * We also accept "currency_type" defensively because gateway
     * response formats sometimes expose currency under that
     * field name.
     */
    const validationCurrency =
      String(
        validation.currency ||
        validation.currency_type ||
        ''
      ).toUpperCase();


    if (
      validationCurrency !== 'BDT'
    ) {
      throw createHttpError(
        'Premium payment currency validation failed.',
        400
      );
    }


    /*
     * --------------------------------------------------------
     * SAVE SUCCESSFUL PAYMENT
     * --------------------------------------------------------
     *
     * At this point the gateway has been independently verified.
     *
     * We can finally mark OUR local PremiumPayment as paid.
     */
    payment.status =
      'paid';


    /*
     * Save the validation ID so the transaction can be traced
     * later during testing/debugging.
     */
    payment.gatewayValidationId =
      validation.val_id ||
      validationId.trim();


    /*
     * SSLCOMMERZ may provide a bank transaction identifier.
     */
    payment.gatewayBankTransactionId =
      validation.bank_tran_id ||
      null;


    /*
     * Store the gateway's normalized successful status.
     */
    payment.gatewayStatus =
      validationStatus;


    /*
     * Preserve an existing paidAt value if one somehow already
     * exists.
     */
    payment.paidAt =
      payment.paidAt ||
      new Date();


    await payment.save();
  }


  /*
   * ----------------------------------------------------------
   * ACTIVATE PREMIUM MEMBERSHIP
   * ----------------------------------------------------------
   *
   * This happens AFTER the payment has become verified and paid.
   *
   * ensurePremiumMembershipForPayment() is idempotent, so:
   *
   *   success callback
   *   +
   *   duplicate success callback
   *   +
   *   IPN callback
   *
   * still produce only one PremiumMembership.
   */
  const membership =
    await ensurePremiumMembershipForPayment(
      payment
    );


  return {
    payment,
    membership,
  };
}


/*
 * ------------------------------------------------------------
 * MARK PREMIUM PAYMENT FAILED
 * ------------------------------------------------------------
 *
 * Failure callbacks do not activate Premium.
 *
 *
 * If a transaction was already successfully validated as paid,
 * a later failure callback is ignored.
 *
 * This prevents a successful transaction from being downgraded
 * because callbacks arrived in an unusual order.
 */
async function markPremiumPaymentFailed({
  transactionId,
  gatewayStatus,
}) {
  const payment =
    await findPremiumPaymentByTransactionId(
      transactionId
    );


  if (
    payment.status !== 'paid'
  ) {
    payment.status =
      'failed';

    payment.gatewayStatus =
      gatewayStatus ||
      'FAILED';

    payment.failedAt =
      payment.failedAt ||
      new Date();

    await payment.save();
  }


  return payment;
}


/*
 * ------------------------------------------------------------
 * MARK PREMIUM PAYMENT CANCELLED
 * ------------------------------------------------------------
 *
 * A cancelled checkout:
 *
 *   - does NOT activate Premium
 *   - does NOT award reward points
 *   - leaves the traveler free to attempt Premium purchase again
 *
 *
 * As with failure handling, an already-paid transaction is never
 * downgraded.
 */
async function markPremiumPaymentCancelled({
  transactionId,
  gatewayStatus,
}) {
  const payment =
    await findPremiumPaymentByTransactionId(
      transactionId
    );


  if (
    payment.status !== 'paid'
  ) {
    payment.status =
      'cancelled';

    payment.gatewayStatus =
      gatewayStatus ||
      'CANCELLED';

    payment.cancelledAt =
      payment.cancelledAt ||
      new Date();

    await payment.save();
  }


  return payment;
}


/*
 * ------------------------------------------------------------
 * INITIATE PREMIUM UPGRADE FOR TRAVELER
 * ------------------------------------------------------------
 *
 * This function starts Premium checkout.
 *
 *
 * Steps:
 *
 * 1. Verify traveler information exists.
 *
 * 2. Make sure the traveler is not already Premium.
 *
 * 3. Clean up old abandoned Premium-payment attempts.
 *
 * 4. Prevent another recent checkout from being opened.
 *
 * 5. Read the CURRENT Premium price from RewardSettings.
 *
 * 6. Generate a backend transaction ID.
 *
 * 7. Create PremiumPayment.
 *
 * 8. Create an SSLCOMMERZ hosted checkout session.
 *
 * 9. Store the gateway session key.
 *
 * 10. Return the hosted checkout URL.
 */
async function initiatePremiumUpgradeForTraveler(
  traveler
) {
  /*
   * Normally authenticateUser guarantees this.
   *
   * The check still makes this service safer if another backend
   * function accidentally calls it incorrectly.
   */
  if (
    !traveler?._id
  ) {
    throw createHttpError(
      'Authenticated traveler information is required.',
      401
    );
  }


  /*
   * ----------------------------------------------------------
   * STEP 1 - ALREADY PREMIUM?
   * ----------------------------------------------------------
   *
   * A traveler with an existing PremiumMembership must not be
   * allowed to buy Premium again.
   */
  const existingMembership =
    await getPremiumMembershipByTravelerId(
      traveler._id
    );


  if (
    existingMembership
  ) {
    throw createHttpError(
      'This account is already a Premium account.',
      409
    );
  }


  /*
   * ----------------------------------------------------------
   * STEP 2 - CLEAN OLD ABANDONED LOCAL ATTEMPTS
   * ----------------------------------------------------------
   */
  await expireOldPremiumPaymentAttempts(
    traveler._id
  );


  /*
   * ----------------------------------------------------------
   * STEP 3 - PREVENT DUPLICATE ACTIVE CHECKOUT
   * ----------------------------------------------------------
   */
  const activePayment =
    await findActivePremiumPaymentAttempt(
      traveler._id
    );


  if (
    activePayment
  ) {
    throw createHttpError(
      `A Premium upgrade payment is already in progress. Please finish or cancel it before starting another payment. An unfinished attempt expires after ${ACTIVE_PREMIUM_PAYMENT_MINUTES} minutes.`,
      409
    );
  }


  /*
   * ----------------------------------------------------------
   * STEP 4 - LOAD CURRENT GLOBAL SETTINGS
   * ----------------------------------------------------------
   *
   * The frontend NEVER decides the Premium price.
   *
   * The authoritative price comes from MongoDB.
   */
  const settings =
    await getRewardSettings();


  /*
   * ----------------------------------------------------------
   * STEP 5 - GENERATE TRANSACTION ID
   * ----------------------------------------------------------
   */
  const transactionId =
    generatePremiumTransactionId();


  /*
   * ----------------------------------------------------------
   * STEP 6 - CREATE TRUSTED LOCAL PAYMENT RECORD
   * ----------------------------------------------------------
   *
   * amount comes from RewardSettings.
   *
   * It does NOT come from req.body.
   */
  const payment =
    await PremiumPayment.create({
      travelerId:
        traveler._id,

      amount:
        settings.premiumUpgradePrice,

      currency:
        'BDT',

      gateway:
        'sslcommerz',

      transactionId,

      status:
        'initiated',
    });


  let gatewaySession;


  try {
    /*
     * --------------------------------------------------------
     * STEP 7 - CREATE SSLCOMMERZ SESSION
     * --------------------------------------------------------
     *
     * createPremiumPaymentSession() is Rafi's additive extension
     * to the project's shared gateway service.
     *
     * Fatema's existing createPaymentSession() remains separate
     * and continues handling booking payments.
     */
    gatewaySession =
      await createPremiumPaymentSession({
        transactionId:
          payment.transactionId,

        amount:
          payment.amount,

        customer: {
          name:
            traveler.name,

          email:
            traveler.email,

          phone:
            traveler.phone,
        },
      });
  } catch (error) {
    /*
     * A local PremiumPayment exists, but gateway-session
     * creation failed.
     *
     * Keep the record for history/debugging instead of deleting
     * it.
     */
    payment.status =
      'failed';

    payment.gatewayStatus =
      'SESSION_INIT_FAILED';

    payment.failedAt =
      new Date();

    await payment.save();

    throw error;
  }


  /*
   * ----------------------------------------------------------
   * STEP 8 - SAVE GATEWAY SESSION KEY
   * ----------------------------------------------------------
   */
  payment.gatewaySessionKey =
    gatewaySession.sessionKey;

  await payment.save();


  /*
   * ----------------------------------------------------------
   * STEP 9 - RETURN CHECKOUT INFORMATION
   * ----------------------------------------------------------
   */
  return {
    payment,

    gatewayPageUrl:
      gatewaySession.gatewayPageUrl,
  };
}


export {
  ACTIVE_PREMIUM_PAYMENT_MINUTES,
  findPremiumPaymentByTransactionId,
  initiatePremiumUpgradeForTraveler,
  markPremiumPaymentCancelled,
  markPremiumPaymentFailed,
  verifyAndCompletePremiumPayment,
};